<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AudioSwitcher.AudioApi.CoreAudio" Version="3.0.3" />
    <PackageReference Include="Microsoft.Recognizers.Text.Number" Version="1.8.13" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Vosk" Version="0.3.38" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Models\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
